### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelectedText' of undefined

### ISSUE THREAD

**Issue by hvcloud** [danseethaler/snippet-generator#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.3
**Thrown From**: [snippet-generator](https://github.com/danseethaler/snippet-generator) package, v0.3.2
**User**: root

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedText' of undefined

```
At /Users/UULLOO/.atom/packages/snippet-generator/lib/snippet-generator.js:22

TypeError: Cannot read property 'getSelectedText' of undefined
    at atom-workspace.snippetGeneratorGenerate (/Users/UULLOO/.atom/packages/snippet-generator/lib/snippet-generator.js:22:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1175:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:319:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -9:39.9.0 core:confirm (input.hidden-input)
     -0:00.2.0 snippet-generator:generate (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "meteor-api",
      "language-babel"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.5 (active)
atom-electron-snippets, v2.0.3 (active)
atom-jade, v0.3.0 (active)
atom-live-server, v1.2.5 (active)
atom-material-syntax, v1.0.2 (inactive)
atom-material-ui, v1.3.9 (active)
atom-nodejs-snippets, v1.4.0 (inactive)
atom-runner, v2.7.1 (inactive)
auto-update-packages, v1.0.1 (active)
autocomplete-modules, v1.6.7 (active)
autocomplete-python, v1.8.40 (active)
browser-plus, v0.0.87 (active)
browser-refresh, v0.9.0 (active)
css-snippets, v1.1.0 (active)
django-templates, v0.5.0 (active)
docblockr, v0.9.1 (active)
emmet, v2.4.3 (active)
file-icons, v2.0.14 (active)
font-awesome-snippet, v0.0.1 (active)
highlight-selected, v0.12.0 (active)
javascript-snippets, v1.2.1 (active)
kite, v0.7.13 (active)
language-babel, v2.54.0 (inactive)
language-jade, v0.7.2 (active)
linter, v1.11.21 (active)
linter-sass-lint, v1.7.4 (active)
linter-spell-html, v0.6.1 (inactive)
linter-tidy, v2.3.0 (active)
markdown-preview-plus, v2.4.1 (active)
markdown-writer, v2.6.3 (active)
mdl-snippets, v0.3.0 (inactive)
meteor-api, v2.20.0 (inactive)
minimap, v4.26.8 (active)
minimap-highlight-selected, v4.5.0 (active)
node-require, v1.0.0 (inactive)
open-in-browser, v0.4.7 (inactive)
open-in-browsers, v0.0.19 (active)
pigments, v0.39.0 (active)
react, v0.16.2 (active)
run-in-atom, v1.0.5 (inactive)
snippet-generator, v0.3.2 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by avatec** [comment]
Same here:

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [snippet-generator](https://github.com/danseethaler/snippet-generator) package 0.3.2


### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedText' of undefined

```
At /Users/avatec/.atom/packages/snippet-generator/lib/snippet-generator.js:22

TypeError: Cannot read property 'getSelectedText' of undefined
    at HTMLElement.snippetGeneratorGenerate (/packages/snippet-generator/lib/snippet-generator.js:22:23)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350017)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348492)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:694296)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:701680)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -2:00.9.0 editor:select-to-end-of-line (input.hidden-input)
     -2:00.2.0 core:copy (input.hidden-input)
     -1:55.7.0 core:paste (input.hidden-input)
     -1:55.5.0 core:save (input.hidden-input)
  4x -1:34.4.0 editor:newline (input.hidden-input)
  4x -1:28.9.0 core:move-up (input.hidden-input)
  2x -1:28.2.0 editor:newline (input.hidden-input)
     -1:24.5.0 core:backspace (input.hidden-input)
  3x -1:24.4.0 editor:newline (input.hidden-input)
  3x -1:20.2.0 core:backspace (input.hidden-input)
     -1:15.8.0 editor:newline (input.hidden-input)
  6x -1:14 core:backspace (input.hidden-input)
     -1:12 core:move-up (input.hidden-input)
     -1:06.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:52.4.0 snippets:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:45.6.0 snippet-generator:generate (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
aligner-css 1.2.1 
animate-css 0.1.4 
atom-minify 0.8.0 
atom-twig 4.2.0 
busy-signal 2.0.1 
css-helper-snippets 0.3.0 
css-in-js 1.4.0 
css-specificity 0.2.2 
css-spy 0.6.0 
ftp-remote-edit 0.14.1 
html-to-css 0.2.2 
ide-css 0.3.2 
intentions 1.1.5 
language-smarty 1.8.0 
php-twig 4.0.0 
platformio-ide-terminal 2.9.1 
sass 0.5.0 
sass-autocompile 0.13.5 
scss-media-queries 0.4.0 
scss-snippets 0.6.0 
ScssBundle 0.5.0 
snippet-generator 0.3.2 
```
